/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
*/

package controller

// Auto-rendered DASHBOARD.md — Phase 3 of the autoresearch flywheel
// refactor.
//
// Why: prior to v0.4.0 the wiki had a static DASHBOARD.md scaffold
// the operator wrote once at bootstrap and never touched again.
// Useful as a header / loop diagram, but it never reflected the
// project's actual state. With the flywheel refactor in place, the
// dashboard becomes a first-class observability artifact: re-
// rendered on every successful proposal commit, embedded in the
// same atomic transaction that lands `proposals/round-N.{yaml,md}`,
// so a human (or another agent) reading the wiki always sees the
// freshest trajectory + searcher state + strategist research.
//
// Three sections:
//
//	1. Header — project name, best eval_loss, current round count,
//	   stagnation indicator.
//	2. Trajectory — last N rounds in a table (round, eval_loss,
//	   lora_rank, learning_rate, kept/reverted decision).
//	3. Searcher state — current sampler, observation count, search
//	   space after HYPOTHESES.md adjustments, top-K configs.
//	4. Strategist research — recent entries from topics/, raw/clips/,
//	   concepts/ that the strategist's wiki-* skills wrote.
//
// The whole file is regenerated from scratch every commit. No
// merge logic, no append-only blocks — the SOURCE of truth is the
// other wiki content (results/, proposals/, HYPOTHESES.md, the
// curated directories). DASHBOARD.md is a derived view.

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	agentofficev1alpha1 "github.com/enterprisewebservice/agent-office-operator/api/v1alpha1"
	"github.com/enterprisewebservice/agent-office-operator/internal/search"
	"github.com/enterprisewebservice/agent-office-operator/internal/wiki"
)

// dashboardTrajectoryRows caps how many rounds the trajectory
// table includes. Older rounds stay in `results/round-N.md` for
// permanent record; the dashboard is a recent-activity window.
const dashboardTrajectoryRows = 20

// dashboardRecentResearch caps how many recent entries are listed
// per strategist-research subdirectory.
const dashboardRecentResearch = 5

// renderDashboard returns the Markdown body of DASHBOARD.md given
// the project's current state. Caller is expected to write it via
// the same `wiki.Transaction` that commits the proposal so the
// dashboard is consistent with the round being committed.
//
// The renderer is intentionally tolerant: empty history,
// missing HYPOTHESES.md, no strategist research — all produce a
// valid (if sparse) dashboard. We never block a round on a
// dashboard render.
func renderDashboard(
	p *agentofficev1alpha1.AutoResearchProject,
	currentRound int,
	cfg QLoRAConfig,
	history []search.Observation,
	hypotheses search.Hypotheses,
	adjustedSpace search.Space,
	tx *wiki.Transaction,
) string {
	var b strings.Builder

	// ── Header ─────────────────────────────────────────────
	b.WriteString(fmt.Sprintf("# Dashboard — `%s`\n\n", p.Name))
	b.WriteString("_Auto-generated by the operator on every round commit. Edit anywhere ABOVE this line at your own risk — the renderer replaces this file in full._\n\n")
	b.WriteString("## Project state\n\n")
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Current round | %d (just proposed) |\n", currentRound))
	b.WriteString(fmt.Sprintf("| Usable observations | %d |\n", len(history)))
	if best := bestObservation(history); best != nil {
		b.WriteString(fmt.Sprintf("| Best eval_loss | **%g** |\n", best.EvalLoss))
		b.WriteString(fmt.Sprintf("| Best lora_rank | %v |\n", best.Params["lora_rank"]))
		b.WriteString(fmt.Sprintf("| Best learning_rate | %v |\n", best.Params["learning_rate"]))
	} else {
		b.WriteString("| Best eval_loss | _(no completed rounds yet)_ |\n")
	}
	stag := search.StagnationCount(history)
	stagStr := fmt.Sprintf("%d rounds without improvement", stag)
	if stag >= defaultStrategistOnStagnation {
		stagStr = "**STAGNATING** — " + stagStr
	}
	b.WriteString(fmt.Sprintf("| Stagnation | %s |\n", stagStr))
	// Go's reference time is "Mon Jan 2 15:04:05 MST 2006" — must
	// use 2006 (not 2026 or anything else) for the year. v0.4.0
	// shipped with "2026-01-02 ..." which rendered as "20206-05-20"
	// because Go interpreted the literal 2026 prefix as digits to
	// pad. Fixed in v0.4.1.
	b.WriteString(fmt.Sprintf("| Last update | %s |\n", time.Now().UTC().Format("2006-01-02 15:04 UTC")))
	b.WriteString("\n")

	// ── Trajectory ─────────────────────────────────────────
	b.WriteString("## Trajectory\n\n")
	if len(history) == 0 {
		b.WriteString("_(no completed rounds yet. Once the first round finishes, this table fills in.)_\n\n")
	} else {
		b.WriteString("Recent completed rounds, newest first:\n\n")
		b.WriteString("| Round | eval_loss | lora_rank | learning_rate | num_steps |\n")
		b.WriteString("|------:|----------:|----------:|--------------:|----------:|\n")
		start := len(history) - dashboardTrajectoryRows
		if start < 0 {
			start = 0
		}
		// Iterate in reverse so newest is at the top.
		for i := len(history) - 1; i >= start; i-- {
			obs := history[i]
			lr, _ := obs.Params["learning_rate"].(float64)
			b.WriteString(fmt.Sprintf("| %d | %g | %v | %g | %v |\n",
				i+1, obs.EvalLoss,
				obs.Params["lora_rank"],
				lr,
				obs.Params["num_training_steps"]))
		}
		if len(history) > dashboardTrajectoryRows {
			b.WriteString(fmt.Sprintf("\n_Truncated to last %d rounds. Older rounds remain in `results/round-N.md`._\n", dashboardTrajectoryRows))
		}
		b.WriteString("\n")
	}

	// ── Searcher state ─────────────────────────────────────
	b.WriteString("## Searcher state\n\n")
	mode := "TPE (goptuna)"
	if len(history) < defaultWarmupTrials {
		mode = fmt.Sprintf("Random (warmup — %d/%d trials)", len(history), defaultWarmupTrials)
	}
	b.WriteString(fmt.Sprintf("- **Sampler**: %s\n", mode))
	b.WriteString(fmt.Sprintf("- **Observations seen**: %d\n", len(history)))
	b.WriteString(fmt.Sprintf("- **HYPOTHESES.md applied**: %v", hypotheses.GeneratedAfterRound > 0))
	if hypotheses.GeneratedAfterRound > 0 {
		b.WriteString(fmt.Sprintf(" (after round %d, %d adjustments)",
			hypotheses.GeneratedAfterRound, len(hypotheses.AdjustSearchSpace)))
	}
	b.WriteString("\n\n")

	// Show the effective search space (post-HYPOTHESES).
	b.WriteString("### Current search space\n\n")
	b.WriteString("| Param | Range / Choices | Notes |\n")
	b.WriteString("|-------|-----------------|-------|\n")
	intNames := dashboardSortedKeys(adjustedSpace.Ints)
	for _, name := range intNames {
		spec := adjustedSpace.Ints[name]
		note := ""
		if orig, ok := defaultQLoRASpace().Ints[name]; ok {
			if orig.Low != spec.Low || orig.High != spec.High {
				note = fmt.Sprintf("narrowed from [%d, %d]", orig.Low, orig.High)
			}
		}
		rng := fmt.Sprintf("[%d, %d]", spec.Low, spec.High)
		if spec.Step > 0 {
			rng += fmt.Sprintf(" step %d", spec.Step)
		}
		b.WriteString(fmt.Sprintf("| `%s` (int) | %s | %s |\n", name, rng, note))
	}
	floatNames := dashboardSortedKeys(adjustedSpace.Floats)
	for _, name := range floatNames {
		spec := adjustedSpace.Floats[name]
		note := ""
		if orig, ok := defaultQLoRASpace().Floats[name]; ok {
			if orig.Low != spec.Low || orig.High != spec.High {
				note = fmt.Sprintf("narrowed from [%g, %g]", orig.Low, orig.High)
			}
		}
		mode := "uniform"
		if spec.Log {
			mode = "log-uniform"
		}
		b.WriteString(fmt.Sprintf("| `%s` (float, %s) | [%g, %g] | %s |\n",
			name, mode, spec.Low, spec.High, note))
	}
	catNames := dashboardSortedKeys(adjustedSpace.Categoricals)
	for _, name := range catNames {
		spec := adjustedSpace.Categoricals[name]
		note := ""
		if orig, ok := defaultQLoRASpace().Categoricals[name]; ok {
			if len(orig.Choices) != len(spec.Choices) {
				note = fmt.Sprintf("changed from %d choices", len(orig.Choices))
			}
		}
		b.WriteString(fmt.Sprintf("| `%s` (categorical) | %s | %s |\n",
			name, strings.Join(spec.Choices, ", "), note))
	}
	b.WriteString("\n")

	// Top-K best configs to date.
	if len(history) > 0 {
		topK := topKObservations(history, 5)
		b.WriteString(fmt.Sprintf("### Top %d configurations\n\n", len(topK)))
		b.WriteString("| Rank | eval_loss | lora_rank | learning_rate | round |\n")
		b.WriteString("|-----:|----------:|----------:|--------------:|------:|\n")
		for i, obs := range topK {
			lr, _ := obs.observation.Params["learning_rate"].(float64)
			b.WriteString(fmt.Sprintf("| %d | %g | %v | %g | %d |\n",
				i+1, obs.observation.EvalLoss,
				obs.observation.Params["lora_rank"], lr, obs.roundIdx+1))
		}
		b.WriteString("\n")
	}

	// ── Strategist research ────────────────────────────────
	b.WriteString("## Strategist research\n\n")
	if len(hypotheses.AdjustSearchSpace) == 0 && hypotheses.Hypothesis == "" {
		b.WriteString("_(strategist has not run yet — wait for cadence (every 5 rounds) or stagnation (3+ rounds without improvement) to trigger the first turn.)_\n\n")
	} else {
		if hypotheses.Hypothesis != "" {
			b.WriteString("### Current hypothesis\n\n")
			b.WriteString("> " + strings.ReplaceAll(strings.TrimSpace(hypotheses.Hypothesis), "\n", "\n> ") + "\n\n")
		}
		if len(hypotheses.References) > 0 {
			b.WriteString("### Cited artifacts\n\n")
			for _, ref := range hypotheses.References {
				b.WriteString(fmt.Sprintf("- [`%s`](./%s)\n", ref, ref))
			}
			b.WriteString("\n")
		}
	}

	// List recent files in strategist-managed directories.
	if tx != nil {
		writeResearchSection(&b, "raw/clips", "Recent clips", tx)
		writeResearchSection(&b, "topics", "Recent topics", tx)
		writeResearchSection(&b, "concepts", "Concept pages", tx)
	}

	// ── Footer ─────────────────────────────────────────────
	b.WriteString("---\n\n")
	b.WriteString("Generated by `agent-office-operator` v0.4.0+ (Phase 3).\n")
	return b.String()
}

// writeResearchSection appends a sub-section listing recent files
// in `dir` (relative to the wiki root). Skips silently if the
// directory doesn't exist or contains no relevant files.
func writeResearchSection(b *strings.Builder, dir, heading string, tx *wiki.Transaction) {
	entries, err := tx.List(dir)
	if err != nil || len(entries) == 0 {
		return
	}
	// Filter to .md files only — the wiki-clip/write skills land
	// Markdown; binary attachments live alongside but don't
	// belong in the recent-research list.
	mdFiles := []string{}
	for _, e := range entries {
		if strings.HasSuffix(e, ".md") {
			mdFiles = append(mdFiles, e)
		}
	}
	if len(mdFiles) == 0 {
		return
	}
	// Sort alphabetically (file names usually have date prefix
	// from the wiki-clip skill convention) and pick the last N
	// — newest at the top.
	sort.Strings(mdFiles)
	start := len(mdFiles) - dashboardRecentResearch
	if start < 0 {
		start = 0
	}
	b.WriteString(fmt.Sprintf("### %s\n\n", heading))
	for i := len(mdFiles) - 1; i >= start; i-- {
		path := filepath.Join(dir, mdFiles[i])
		b.WriteString(fmt.Sprintf("- [`%s`](./%s)\n", path, path))
	}
	b.WriteString("\n")
}

// scoredObservation pairs an observation with its round index so
// topKObservations can produce both for the dashboard table.
type scoredObservation struct {
	observation search.Observation
	roundIdx    int
}

// topKObservations returns the k best (lowest eval_loss)
// observations + their round indices. Stable order: ties broken by
// earlier round index.
func topKObservations(history []search.Observation, k int) []scoredObservation {
	if k > len(history) {
		k = len(history)
	}
	idx := make([]scoredObservation, len(history))
	for i, obs := range history {
		idx[i] = scoredObservation{observation: obs, roundIdx: i}
	}
	sort.SliceStable(idx, func(a, b int) bool {
		if idx[a].observation.EvalLoss != idx[b].observation.EvalLoss {
			return idx[a].observation.EvalLoss < idx[b].observation.EvalLoss
		}
		return idx[a].roundIdx < idx[b].roundIdx
	})
	return idx[:k]
}

// dashboardSortedKeys returns the sorted keys of any map[string]V. Used to
// produce stable iteration order in the dashboard tables.
func dashboardSortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
