---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agentoffice.ai
  resources:
  - agentworkstations
  - memorymodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentoffice.ai
  resources:
  - agentworkstations/finalizers
  - memorymodules/finalizers
  verbs:
  - update
- apiGroups:
  - agentoffice.ai
  resources:
  - agentworkstations/status
  - memorymodules/status
  verbs:
  - get
  - patch
  - update
