apiVersion: agentoffice.ai/v1alpha1
kind: AgentWorkstation
metadata:
  labels:
    app.kubernetes.io/name: agent-office-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentworkstation-sample
spec:
  # TODO(user): Add fields here
